// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvS2Mk02IonW-fXl008mT2hwDyL2_F934',
    appId: '1:745937725793:android:6eb7f8931c3349fdc6bd20',
    messagingSenderId: '745937725793',
    projectId: 'dukkantek-task-1ac40',
    storageBucket: 'dukkantek-task-1ac40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx248HGF4Jk8th1AQ_g24oCEPqjSvs8RA',
    appId: '1:745937725793:ios:d62f330a9be0bb15c6bd20',
    messagingSenderId: '745937725793',
    projectId: 'dukkantek-task-1ac40',
    storageBucket: 'dukkantek-task-1ac40.appspot.com',
    iosClientId: '745937725793-vsqqqn9v89cs8qbo75muesjphk2i36ib.apps.googleusercontent.com',
    iosBundleId: 'com.signup.task.signupProjectTask',
  );
}
